AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Typescript AWS SAM Demo
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  HelloFrom:
    Description: Who to say hello from
    Type: String
    Default: typescript

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 180
    MemorySize: 128
    CodeUri: ../.aws-sam/build
    Environment:
      Variables:
        HELLO_FROM: !Sub '${HelloFrom}'
  SimpleTable:
    SSESpecification:
      SSEEnabled: true

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/http/hello-name.handler
      Environment:
        Variables:
          TABLE: !Ref HelloTable
      Events:
        HelloWorldHttpApi:
          Type: HttpApi
          Properties:
            Path: /hello-world/{to}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy: #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html
            TableName: !Ref HelloTable

  HelloTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint for demo"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/hello-world/Bangles"
